// Generated by CoffeeScript 1.10.0
(function() {
  Template.userview_polls.onCreated(function() {
    return this.autorun((function(_this) {
      return function() {
        return _this.subscribe('allPolls');
      };
    })(this));
  });

  Template.userview_polls.helpers({
    path_polls_index: function() {
      return FlowRouter.path('polls_index');
    },
    poll: function() {
      return Polls.findOne(FlowRouter.getParam('pollId'));
    }
  });

  Template.userview_polls.onRendered(function() {
    $('input[class^="option"]:first').attr('checked', true);
    return new Vue({
      el: '#polls_vote_form',
      data: {
        pollvoter: ''
      },
      methods: {
        submit: function(e) {
          var $opt, counter, poll, pollvoter, selectedOpt;
          e.preventDefault();
          if (this.pollvoter) {
            poll = Polls.findOne(FlowRouter.getParam('pollId'));
            pollvoter = this.pollvoter;
            $opt = $('input[class^="option"]');
            selectedOpt = $opt.index($opt.filter(':checked'));
            counter = poll.options_poll[selectedOpt].optioncount + 1;
            poll.options_poll[selectedOpt].push('persons', pollvoter);
            poll.options_poll[selectedOpt].set('optioncount', counter);
            if (poll.validate()) {
              poll.save();
              return FlowRouter.go('userview_diagram');
            }
          } else {
            return alert('Your name can\'t be empty!');
          }
        }
      }
    });
  });

}).call(this);
