// Generated by CoffeeScript 1.10.0
(function() {
  Template.userview_polls.onCreated(function() {
    return this.autorun((function(_this) {
      return function() {
        return _this.subscribe('allPolls');
      };
    })(this));
  });

  Template.userview_polls.helpers({
    path_polls_index: function() {
      return FlowRouter.path('polls_index');
    }
  });

  Template.userview_polls.onRendered(function() {
    return new Vue({
      el: '#polls_vote_form',
      data: {
        poll: {},
        pollId: FlowRouter.getParam('pollId'),
        pollvoter: ''
      },
      created: function() {
        this.subscriptionPoll = Meteor.subscribe('singlePoll', this.pollId);
        return Tracker.autorun((function(_this) {
          return function() {
            return _this.poll = Polls.findOne(_this.pollId);
          };
        })(this));
      },
      methods: {
        submit: function(e) {
          var $opt, selectedOpt;
          e.preventDefault();
          if (this.pollvoter) {
            ({
              pollvoter: this.pollvoter
            });
            $opt = $('input[class^="option"]');
            selectedOpt = $opt.index($opt.filter(':checked'));
            console.log($opt);
            alert(selectedOpt);
            poll.options_poll[selectedOpt].push('persons', pollvoter);
            poll.options_poll[selectedOpt].optioncount++;
            if (poll.validate()) {
              poll.save();
              return FlowRouter.go('polls_index');
            }
          } else {
            return alert('Your name can\'t be empty!');
          }
        }
      }
    });
  });

}).call(this);
